export const AdSetTypes = {
    optimiztion: {
         "n": "NONE",
         "ai": "APP_INSTALLS",
         "ba": "BRAND_AWARENESS",
         "arl": "AD_RECALL_LIFT",
         "c": "CLICKS",
         "eu": "ENGAGED_USERS",
         "er": "EVENT_RESPONSES",
         "i": "IMPRESSIONS",
         "lg": "LEAD_GENERATION",
         "lc": "LINK_CLICKS",
         "of": "OFFER_CLAIMS",
         "ofsc": "OFFSITE_CONVERSIONS",
         "pe": "PAGE_ENGAGEMENT",
         "pl": "PAGE_LIKES",
         "pste": "POST_ENGAGEMENT",
         "r": "REACH",
         "si": "SOCIAL_IMPRESSIONS",
         "vv": "VIDEO_VIEWS",
         "ad": "APP_DOWNLOADS",
         "tscvv": "TWO_SECOND_CONTINUOUS_VIDEO_VIEWS",
         "lpv": "LANDING_PAGE_VIEWS",
         "v": "VALUE",
         "t": "THRUPLAY",
         "r": "REPLIES",
         "de": "DERIVED_EVENTS",
    }
}